### ISSUE TITLE
Initial Setting Docs

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#1]
깃허브 세팅 완료 및 개인 브랜치 생성해 드렸습니다!! 

프론트 화면은 `npm run dev`로 동작하고, DB까지 실행시키고 싶으신 경우
1) Readme 참고하시어 scoop 설치합니다.
2) 터미널에서 `pscale connect paldo-games main --port 3309` 실행
3) vscode등에서 `npm run prisma` 실행
하시면 됩니다~ 

NextAuth는 아직 설치되지 않은 상태니 다희님 진행하시면서 설치해서 사용하셔야 할 거예요!
DB까지 실행시키지 않아도 프론트 화면 작동하니 참고해주세요!

**Comment by Exist95** [comment]
1-1. pscale org switch paldo-games

**Comment by Exist95** [comment]
windows에서는 powershell에서 1-1, 2번을 진행합니다~

**Comment by devyuriii** [comment]
DB Production 했습니다~
