### ISSUE TITLE
NextAuth Token 문의

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#10]
NextAuth를 사용한 SNS 연동 로그아웃 문제 해결 되셨을까용?

로그인 연장 로직까지 혹시 파악하셨다면 정규 회의 시간에 브리핑 부탁 드립니다!

래퍼런스 있는 경우 코멘트로 달아주시면 좋을 듯 합니다~

**Comment by hongdahee** [comment]
로그아웃 문제는 아직 해결이 안 됐습니다ㅠㅠ
토큰은 nextAuth의 signIn, signOut 함수에서 자동 처리된다고 이해했습니다.
그리고 데이터베이스를 쓰는 경우엔 jwt를 사용하지 않아도 된다고 합니다.

nextAuth와 prisma 연결 레퍼런스
https://cpro95.tistory.com/516
prisma adapter 공식 문서
https://next-auth.js.org/adapters/prisma
