### ISSUE TITLE
추가 게임 변경 건의

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#11]
MVP 이후 게임 추가할 때, 퀴즈와 가위바위보, 틱택토 추가하기로 했는데

틱택토 로직이 복잡할 것 같아서 2048로 변경하는 거 어떤지 건의 드립니다!
포인트 내기도 좋고 잘 설명된 유튜브와 블로그 글이 많더라구용

제가 본 레퍼런스입니다! https://programming119.tistory.com/185

**Comment by Exist95** [comment]
1. 포인트 주는 방식은 어떻게 될까요?? 일정 점수를 기준으로 잡아 그 점수를 넘으면 포인트를 주는 방식으로 하나요? 
2. 그리고 점수를 달성했을 때, 포인트는 몇 점을 주어야 할까요?

**Comment by devyuriii** [comment]
> 1. 포인트 주는 방식은 어떻게 될까요?? 일정 점수를 기준으로 잡아 그 점수를 넘으면 포인트를 주는 방식으로 하나요?
> 2. 그리고 점수를 달성했을 때, 포인트는 몇 점을 주어야 할까요?

1. 게임을 진행하다가 2048을 병합하면 포인트를 획득하고, 게임을 종료하려 합니다.
2. 숫자야구와 동일하게 포인트 지급하면 어떨까 싶습니다!
