### ISSUE TITLE
Next.js 폴더 구조와 export 방식에 대해 어느정도 약속을 가져가면 좋을것 같습니다.

### ISSUE THREAD

**Issue by leezer94** [haileyport/PaldoGames#15]
### Folder Structure

**참고할만한 블로그**

- [https://giancarlobuomprisco.com/next/a-scalable-nextjs-project-structure](https://giancarlobuomprisco.com/next/a-scalable-nextjs-project-structure)

---

### Export Default / Named Export

**참고할만한 블로그**

- [https://leedr0730.medium.com/디렉토리-파일-export-하기-index-js-사용-2e698a8e2cbd](https://leedr0730.medium.com/%EB%94%94%EB%A0%89%ED%86%A0%EB%A6%AC-%ED%8C%8C%EC%9D%BC-export-%ED%95%98%EA%B8%B0-index-js-%EC%82%AC%EC%9A%A9-2e698a8e2cbd)
- https://www.bundleapps.io/blog/use-named-exports-over-default-exports-in-javascript

---

### 현재 제가 가지고 있는 폴더 구조 (  src 폴더 하위 )
![Screen Shot 2022-09-08 at 5 12 02 AM](https://user-images.githubusercontent.com/83988230/188969386-249a3c5e-f317-4863-9e8b-19ae0089402d.png)

한번 같이 고민해보면 좋을것 같습니다!

**Comment by Exist95** [comment]
정말 중요할 것 같네요~ 지금은 딱히 떠오르는 게 없어서 생각 좀 해보고 코멘트 달겠습니다!!
