### ISSUE TITLE
깃허브 PR 규칙 추가 건 공지

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#16]
**1. Merge 전 리뷰 필수 규칙**
이제 깃허브에서 PR 날리실 때, 리뷰어가 1명 이상 필수로 필요하도록 설정했습니다.
리뷰가 없으면 아래 사진 상에 체크표시된 부분이 X표시되고 merge 불가능합니다!

![image](https://user-images.githubusercontent.com/50188104/189013446-19481ea1-fcf5-4e44-ba53-1cfad558d7d0.png)

사진은 어제 다희님이 올려주신 auth PR이고 제가 리뷰어로 참석한 모습입니당.

**2. develop 브랜치 merge 규칙**
develop 브랜치는 merge가 commit으로 남지 않게 해두었습니다

![image](https://user-images.githubusercontent.com/50188104/189013516-d2082ddb-159e-4e6d-bde3-3684ada5417f.png)

규칙 적용 전(건희님 PR merge한 commit) : merge 시에 commit 메세지를 입력해야 했습니다.
규칙 적용 후(이후 다희님 PR) : commit 메세지를 적지 않아도 PR을 날려주신 다희님의 commit만 적용되었습니다.

확인하신 후 코멘트 남겨주시면 이슈는 클로즈 하겠습니다~

**Comment by Exist95** [comment]
확인했습니다!

**Comment by leezer94** [comment]
확인했습니다!

**Comment by hongdahee** [comment]
확인했습니다!
