### ISSUE TITLE
게임 타이틀 및 버튼 스타일 관련

### ISSUE THREAD

**Issue by Exist95** [haileyport/PaldoGames#17]
최대한 이질감이 덜 느껴지도록
타이틀이나 버튼 스타일은 맞추고자 하는데 어떠신가요?
의견 남겨주세요!!

**Comment by hongdahee** [comment]
맞추는 게 통일성 있고 좋을 거 같습니다!

**Comment by devyuriii** [comment]
버튼은 컴포넌트로 제작한 것 계속해서 재사용하면 좋지 않을까요?
통일성은 저도 중요하다고 생각해요!

**Comment by leezer94** [comment]
넵 동의 합니다 따로 게임용 버튼 이나 홈ui용 버튼 이런식으로 구분하면 좋을것 같습니다.

**Comment by devyuriii** [comment]
커뮤니티 진행 척도랑 같이 피그마에서 UI 보며 이번주에 이야기 나누면 좋을 듯 싶네요!

**Comment by hongdahee** [comment]
게임 끝나면 나오는 결과창도 어떻게 표시할지 통일하면 좋을 거 같습니다. 
결과창을 다른 페이지로 새로 만드는 건 어떨까요?

**Comment by Exist95** [comment]
결과창 좋은 것 같아요!  
다만 다른 페이지로 갈지, 모달 창으로 띄울지는 상의해 볼 필요가 있을 것 같네요!! 
좋은 의견들 감사합니다. 
오늘 회의 때 봬요!
