### ISSUE TITLE
Next.js 에서 recoil 로 상태관리시에 'Duplicate Atom key' 워닝 관련

### ISSUE THREAD

**Issue by leezer94** [haileyport/PaldoGames#18]
Next.js 에서 recoil 로 상태관리시에 'Duplicate Atom key' 워닝이 콘솔에 찍히게 되는데, 
기능상에 문제는 없고 현재까지 알아본 정보로는 

1. 유니크한 key 값을 부여 한다.
2.  Warning 을 disable 해준다.

두가지 방법이 있는것 같은데 두가지 방법 모두 임시방편 인것 같고 두번째 방법또한 실제로 duplicated 된 atom이 있을경우에는 warning이 발생하지 않아서 문제가 되는것 같습니다.

아직 까지는 오픈이슈 인것 같아

그래도 워닝를 무시하고 싶다면 아래 방법을 참고하면 될 것 같습니다

참고 : hhttps://github.com/facebookexperimental/Recoil/issues/733#issuecomment-1125481011

![Screen Shot 2022-09-11 at 6 14 41 PM](https://user-images.githubusercontent.com/83988230/189520140-1bebcef6-d223-484c-a5dc-e8f79e37002e.png)
https://github.com/tooktak/find-game-friend-front/issues/22#issuecomment-1183477181

**Comment by devyuriii** [comment]
확인했습니다! 관련해서 알아봐주셔서 감사합니다 (__)
