### ISSUE TITLE
구구단 게임 타이머 관련 질문

### ISSUE THREAD

**Issue by hongdahee** [haileyport/PaldoGames#20]
구구단 게임에 3초 타이머 기능을 구현했는데, 이 타이머가 구구단 화면 렌더링 되자마자 바로 실행돼도 괜찮을까요?
게임 시작 버튼을 누르면 타이머가 실행되도록 해 보려 했는데 useEffect를 써서 타이머를 구현한 거라 어렵네요ㅠㅠ
게임 화면에서 구구단 게임 시작을 누르고 게임이 바로 시작돼도 괜찮을지 아니면 구구단 게임 화면에서 또 게임 시작 버튼이 있는 게 좋을지 의견 부탁 드립니다

**Comment by Exist95** [comment]
게임 내에서 시작 버튼이 따로 있으면 만족도가 더 높지 않을까요..? 😆

**Comment by hongdahee** [comment]
네 그럴 거 같아요 답변 감사합니다 ㅎㅎ 건희님이 도움 주셔서 버튼 해결했습니다!
