### ISSUE TITLE
현재 Windows와 Mac OS에서 보이는 화면이 조금 다릅니다. 어떻게 해결해야 할까요??

### ISSUE THREAD

**Issue by Exist95** [haileyport/PaldoGames#21]
건희님과 화면공유를 하다가 알게 된 사실입니다.
커뮤니티 사이트의 예시1과 예시2의 위치가 OS에 따라 다르게 나타나는 것 같습니다.

**Comment by devyuriii** [comment]
예시 사진을 첨부해주실 수 있나요??

**Comment by Exist95** [comment]
커뮤니티 페이지에서 탭 위치를 말한 건데, 해결된 것 같습니다.
