### ISSUE TITLE
커뮤니티 필요 데이터 질의

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#22]
커뮤니티 탭에서 필요한 데이터가 어떤 게 있나요?

오늘 브리핑 들으면서 유추한 것은 아래 적어둔 것 정도입니다.
- 글 제목
- 글 내용
- 글쓴이
- 깃허브 링크 (User 에 추가?)

추가적으로 필요한 것 코멘트 부탁드립니다!

**Comment by devyuriii** [comment]
**이슈**

기능: 커뮤니티 탭에서 프로필 클릭 시 깃허브로 이동하는 기능

이슈 내용: 카카오 로그인으로 회원가입 하는 경우 깃허브 주소를 저장할 수 없다는 이슈가 있습니다.

확인 부탁드립니다.

**Comment by leezer94** [comment]
![Screen Shot 2022-09-19 at 7 46 49 PM](https://user-images.githubusercontent.com/83988230/191001371-16e8b581-defb-479b-8aba-f98b440acffc.png)

현재까지 필요한 정보들은 이정도가 될것같고, 어느 소셜로그인을 이용하냐에 따라 소셜id key값이 달라질것 같습니다.
깃허브를 이용하게 된다면 깃허브 주소까지 가져올수 있으면 좋을것 같네요
