### ISSUE TITLE
페이지 라우팅 질문

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#26]
기존에 올려주셨던 폴더구조에서 게임 페이지 라우팅이 아래와 같이 되어있습니다.

![image](https://user-images.githubusercontent.com/50188104/190300982-11eb5482-d496-4b6d-b140-4da26b5a4bf6.png)

같은 양식으로 baseball 게임을 넣어주었는데, url은 변경되는데 페이지는 끝말잇기로 랜딩이 됩니다.

대괄호를 빼면 페이지 라우팅 자체가 에러나구요.

현재 게임페이지 라우팅이 어떤 방식으로 되어있는지, 대괄호로 라우팅 하신 이유가 무엇이었는지 질문 드립니다!

**Comment by leezer94** [comment]
대괄호는 혼자 이것저것 해보다가 변경안하고 남겨둔거 같네요 ㅎㅎ;

해당 게임페이지로 넘어가는 로직은
Components 폴더 하위의 Games/GamesMain/GamesMain.js 에서 아래 스크린샷과 같이 적용해주시면 될것 같습니다.
![Screen Shot 2022-09-15 at 5 24 10 PM](https://user-images.githubusercontent.com/83988230/190354960-6378e98c-19ba-49b8-8663-4c1be05288b3.png)

페이지 구성은
![Screen Shot 2022-09-15 at 5 29 26 PM](https://user-images.githubusercontent.com/83988230/190355090-7adf0516-dee9-440c-b7ab-b00fe0cec49f.png)
아래와 같이 해주시면 될 것 같습니다!

개선될 부분 남겨주시면 감사합니다!
