### ISSUE TITLE
커뮤니티 DB 생성 중 이슈

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#27]
# 서론

현재 카카오 로그인 시 이름과 프로필 사진을 유저 선택 요소로 받아오고 있습니다.

그래서 지난 회의 때 다음과 같이 처리하기로 했습니다.

각각의 선택 요소가 DB에서 확인 되지 않는 경우
프로필 사진: 더미 사진으로 대체
이름: 이메일 앞부분으로 지정

그러나 커뮤니티 DB 생성 시에 문제가 있어서 이슈 올려 드립니다.   
  
------------------------------------------
# 문제상황 브리핑  

### **질문: 커뮤니티 탭에서 상세 글 보기를 클릭하면 작성자의 이름이 나오게 설계되어 있나요?**  

작성자를 User 테이블의 name 컬럼으로 연결하려고 했으나, 해당 컬럼이 Unique하지 않아서 실패했습니다.

단순히 컬럼을 Unique로 지정하면 문제가 일단 해결이 되지만, 이 과정에 문제가 있다고 판단되어 이슈 올리게 되었습니다.

1) 이름을 받아오는 경우
- 카카오, 깃허브 로그인은 이름이 중복될 가능성이 존재합니다. 
- 따라서 Unique 컬럼이 아닙니다.

2) 이름을 받지 못하는 경우
- test@example.com 가 이메일인 경우 test를 이름으로 저장한다고 가정합니다.
- 이메일 도메인이 다른 경우 중복되는 이름이 존재하게 될 수 있습니다.
- 따라서 Unique 컬럼이 되긴 애매합니다.

-----------------------------------------
# 결론  

커뮤니티 상세 글 보기에서 사용자 이름이 들어간다면, 아래와 같이 구조를 잡을 예정입니다.

[Community Table]
- id: uuid
- title: string
- content: string
- editor: (User Table - id)

커뮤니티 페이지 구축하실 때, Community Get과 함께 UserID를 파라미터로 특정 유저를 GET하는 API를 사용하시면 됩니다.

외에 좋은 아이디어 있으시면 말씀해주세요!

**Comment by Exist95** [comment]
좋은 생각인 거 같습니다! 추가 아이디어 없습니다~
