### ISSUE TITLE
로그인 로직 이슈

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#28]
현재 깃허브 로그인과 카카오 로그인 두 가지를 제공하고 있는데,
각각 별개의 유저로 취급되는 문제가 있습니다.

해결법 아이디어 있을까요?

**Comment by leezer94** [comment]
글쓰기 컴포넌트에서도 해당 문제가 영향이 있는데, 별개의 유저로 취급해서 물론 중복해서 글을 쓸 수는 있겟지만 같은 유저가 두개의 아이디를 가지고 글 을 쓰는것은 추후에 문제가 될 수 있을거 같습니다.

제가 지금 생각하기로는 
1. 깃허브 , 카카오톡 중 하나만 선택
   -  깃허브 : 대상이 코드스테이츠 수강생인 만큼 더 의미가 있지 않을까 싶음.
   -  카카오톡  :  적용 대상이 더 커질수 있다. ( 확장 가능성 ? )

2. 다른 유저 취급 한다.
  - 어차피 같은 인물일지라도 다른 계정으로 로그인 하기 때문에 다른 유저 취급을 해준다.

3. 2차인증을 진행 ( 가능성은 적음 )
  - 핸드폰인증 ( 러닝커브 높은 , 비용발생 가능성 있음 )
  - 주민번호 인증 ( 러닝커브 높음 ? , 저장하기 예민한 데이터 )

4. 유효성 검사를 진행해서 같은 데이터를 가진 계정끼리 연동
 - 우리가 가져올수 있는 데이터 중 이메일이 그나마 같을 가능성이 큰 정보는 이메일 일텐데 이메일이 같은 유저에 한해서만 연동을 하고, 그외는 다른 유저로 처리

이렇게 생각해봤습니다.

**Comment by devyuriii** [comment]
정 안되면 말씀하신 것처럼 한 가지 SNS만 연동해야겠네요... 

생각해보니 다른 많은 플랫폼에서도 구글 로그인 계정과 카카오 로그인 계정이 분리되어 있고, 자체 플랫폼 회원가입을 진행한 후 계정 연동을 해야 같은 계정으로 인식하는 형태를 많이 띄더라구요.


덧붙여서 현재는 로그인 하지 않아도 게임 플레이가 가능한데,
포인트를 차감하는 로직이 들어가면 로그인 하지 않은 경우 에러가 발생합니다.

메인 화면 외 다른 기능을 사용하려면 무조건 로그인 하는게 좋을지, 일부 기능에만 로그인 확인을 걸어둘지도 같이 논의해보면 좋겠네요.

**Comment by leezer94** [comment]
게임플레이같은 경우도 게임 화면에는 진입이 가능하되, 로그인 하지 않으면 입장 ? 하지 못하게 하는 방향도 좋을것 같습니다.

한가지 소셜로만 로그인 진행하는것도 좋다고 생각합니다.

**Comment by devyuriii** [comment]
/game 까진 접속이 되고 게임 컴포넌트 클릭할 때 세션 여부 확인해주면 되겠네용

**Comment by devyuriii** [comment]
로그인 깃허브만 허용하는걸로 회의 결과 나왔습니다~!

**Comment by devyuriii** [comment]
> 게임플레이같은 경우도 게임 화면에는 진입이 가능하되, 로그인 하지 않으면 입장 ? 하지 못하게 하는 방향도 좋을것 같습니다.
> 
> 한가지 소셜로만 로그인 진행하는것도 좋다고 생각합니다.

이것도 승인되었습니다~!
