### ISSUE TITLE
폴더구조 변경 건의

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#29]
저희 프로젝트 진행 중 폴더 구조가 혁신적으로 바뀐 적이 한 번 있습니다.

신경써서 바꿔주셨는데 너무 atomic한 구조라 오히려 활용이 어렵다는 생각이 듭니다😭

또한 컴포넌트로 제작된 Button, Flex, Form 등의 파일들에 대해 의문이 생겨 함께 여쭙습니다!
- 해당 컴포넌트들은 어플리케이션 내에서 중복해서 사용할 수 있는 CDD 요소가 아닌, inline으로 CSS를 수정할 수 있게 되어있습니다.
- 위 파일들에 대한 설명을 들을 수 있을까요?

**Comment by Exist95** [comment]
현재 이슈가 많으므로, 정기 회의인 수요일 이전에 한 번 개별 진행 및 문제를 브리핑 하는 시간이 있었으면 좋겠네요.. 랭킹도 랜더링 문제로 리팩토링 해야 할 것 같습니다.ㅠㅠ

**Comment by devyuriii** [comment]
export 기준도 같이 얘기해보면 좋겠어요~

**Comment by devyuriii** [comment]
export 는 wildcard 써서 내보내는 걸로 상의했습니다!

**Comment by devyuriii** [comment]
컴포넌트는 재사용 가능한 컴포넌트로 변경하기로 했습니다!
