### ISSUE TITLE
배포 시 참고자료

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#3]
planet scale 배포 시 참고할 자료입니당 

https://velog.io/@jinyinshu/Deploy1.-pscale

**Comment by Exist95** [comment]
확인했습니다!

**Comment by devyuriii** [comment]
https://birdmee.tistory.com/m/55
https://tobegood.tistory.com/entry/Vercel%EB%A1%9C-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0-feat-react
