### ISSUE TITLE
로또 게임에 결과창이 들어간다면 reset버튼이 필요할까요??

### ISSUE THREAD

**Issue by Exist95** [haileyport/PaldoGames#33]
현재 로또 게임에는 reset버튼과 start버튼이 존재합니다.
만약 결과창을 넣게 된다면 한 번 추첨을 할 때마다 결과창을 보여주게 됩니다.
그렇다면 reset버튼이 필요 없지 않을까요??

또한 reset버튼이 사라지고 결과창을 가져온다고 한다면
지금 발생하는 작은 에러도 문제되지 않을 것 같네용~
어떠신가요???

**Comment by devyuriii** [comment]
애니메이션 에러를 말씀하시는 거죠?
저는 좋다고 생각해요~

reset 페이지에서 게임 이름, 결과, 포인트 외에 더 필요하신 데이터 있나요?

**Comment by Exist95** [comment]
reset 페이지가 따로 필요할까요??

**Comment by devyuriii** [comment]
앗 result 페이지입니다!! 잘못 썼네요 😥

**Comment by Exist95** [comment]
아하! 말씀해주신 3개면 될 것 같아요!!
