### ISSUE TITLE
게임존 썸네일에 대한 질문입니다.

### ISSUE THREAD

**Issue by Exist95** [haileyport/PaldoGames#38]
현재 적절한 로또 썸네일을 구하기 힘들다는 점과  
'심플'이라는 컨셉에 비해 썸네일이 너무 화려하다는 점이 문제라고 생각됩니다.

![image](https://user-images.githubusercontent.com/96723716/191726899-b346f859-c620-4e6d-b8fa-5a11f968b57e.png)
위 방식의 간단한 썸네일로 가져가는 건 어떨까요?

만약 위 썸네일으로 결정될 경우.
![image](https://user-images.githubusercontent.com/96723716/191727432-6462f1ee-7f00-453a-a141-e99205e26ec5.png)
GamesCard 컴포넌트 아랫부분의 이름이 사라지고 다희님께서 만드신 버튼이 조금 내려올 예정입니다.

**Comment by devyuriii** [comment]
심플한 페이지라는 컨셉을 유지하기 위해서는 제안해주신 방향이 더 좋아보이네요!

이미지를 바꾸게 되면 컴포넌트 사이즈도 줄였으면 해요!

**Comment by hongdahee** [comment]
확인했습니다~ 썸네일 깔끔한 게 더 예쁘네요!
