### ISSUE TITLE
2048 게임을 미니게임에 추가 할까요?

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#39]
현재 구현이 끝났고, 포인트 연계 작업 중입니다.

2048 블록을 만든 경우 2048 포인트를 지급하게 할 예정입니다.

**Comment by Exist95** [comment]
결과물이 너무 좋아서 꼭 추가했으면 좋겠어요!!!!

**Comment by devyuriii** [comment]
게임이 종료되면 게임 화면에서 결과가 나타나고 있는데 , 결과창을 연결하는 게 좋을지도 고민이네요 ... 현재 push된 코드는 결과창 연결 안 되어있습니당

**Comment by hongdahee** [comment]
추가했으면 좋겠습니다! 시연 영상 보니까 game over랑 retry 뜨는 것도 깔끔해서 연결 안 해도 괜찮은 거 같습니당

**Comment by devyuriii** [comment]
포인트 지급 로직 및 통일성을 위해 결과창 추가한 상태로 push 했습니당 의견 감사해요!
