### ISSUE TITLE
[긴급] 프로젝트 막바지에 이르렀는데 소감 한 마디씩 주세요!! 

### ISSUE THREAD

**Issue by Exist95** [haileyport/PaldoGames#40]
Footer 위치 수정과 동시에 클릭 시, 후기 페이지로 이동하게 만들어 놓았습니다. (이스터에그 아닌 이스터에그 느낌으로)
이슈 댓글에 소감 남겨주세요!! 구체적이고 길면 더 좋습니다~
자랑하고 싶은 것들도 괜찮아요!!
배포 전까지 부탁드려용~

**Comment by devyuriii** [comment]
이거 왜 긴급이죠 ㅋㅋㅋㅋㅋㅋㅋ 알겠습니당 내일까지 올려둘게요!

**Comment by hongdahee** [comment]
알겠습니다!!

**Comment by devyuriii** [comment]
> 이거 왜 긴급이죠 ㅋㅋㅋㅋㅋㅋㅋ 알겠습니당 내일까지 올려둘게요!

이러고 또 하루가 지나버렸네요 ... 

아이디어가 엄청 많이 쏟아져서 프로젝트 내내 즐거웠어요! 아이디어 빌딩 단계에서 시간상 부족한 부분은 제외해서 아쉬움도 있지만, 최소 기능으로 정의했던 부분은 구현할 수 있어서 재밌었습니다 ㅎㅎ
하나 자랑하자면 저희 홈 화면이 기깔납니다... 센스 좋은 종열님 작품 😏
한 달 빡세게 달려준 팔도게임즈 팀원 분들도 넘 감사해요 🥰

**Comment by hongdahee** [comment]
처음 하는 프로젝트라 어려운 부분도 많았고, 체력적으로도 힘들었지만 너무 즐거웠습니다! 
특히 협업 하는 방법에 대해서도 배울 수 있는 좋은 시간이었습니다
완성된 결과물을 보니까 뿌듯한 마음이 크네요 ㅎㅎ 
그리고 팀원 분들께 모르는 걸 여쭤봤을 때 큰 도움 주셔서 감사합니다 ㅠㅠ 덕분에 많이 배워갑니다!!
많은 분들이 심심하실 때 팔도게임즈 게임존, 커뮤니티 등을 이용해 주시면 정말 뿌듯할 거 같습니다 감사합니다 ☺️

**Comment by leezer94** [comment]
처음하는 프로젝트, 협업 이였는데  어려운 부분도 많았지만, 여러모로 많이 배운것 같습니다!

**Comment by Exist95** [comment]
닫겠습니다!!
