### ISSUE TITLE
로또 결과 페이지 랜딩 문제

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#41]
숫자 게임을 플레이하고 로또를 플레이했는데, 결과페이지로 랜딩할 때 데이터가 바뀌지 않습니다.

결과페이지 연동만 되고 아직 데이터는 연동되지 않은건가요?

**Comment by Exist95** [comment]
그런가요?

**Comment by devyuriii** [comment]
PR안된 내용이었습니다~
