### ISSUE TITLE
커뮤니티 삭제 버그

### ISSUE THREAD

**Issue by devyuriii** [haileyport/PaldoGames#44]
커뮤니티에서 여러 개의 글을 쓰고 난 후, 1개의 글을 삭제하는 경우
작성했던 여러 개의 글이 모두 보이지 않게 됩니다.

새로고침 하면 다시 나타나긴 하는데 아무래도 버그 같아서 제보 드립니다~!

**Comment by leezer94** [comment]
수정완료했습니다.
