### ISSUE TITLE
Footer.style.js 파일 에러 관련입니다.

### ISSUE THREAD

**Issue by hongdahee** [haileyport/PaldoGames#45]
<img width="687" alt="스크린샷 2022-09-25 오후 8 20 17" src="https://user-images.githubusercontent.com/107875003/192140882-25bc09ba-8fa6-4145-a499-8c96758cd5c9.png">

footer가 안 떠서 Footer.style.js 파일을 확인해 보니까 
@media screen and (max-height: 900px) {
    display: none;
  } 
이 부분이 원인인 것 같아서 주석 처리 했더니 footer가 잘 나옵니다. 일단 주석처리 한 상태로 pr 할 예정입니다. 이 부분 확인 부탁 드립니다~

**Comment by Exist95** [comment]
아이고.. 충돌 문제인 줄 알았는데, 미디어쿼리가 문제였군요.. 지레 짐작해서 죄송합니다~~
제 차례에서 해결했으니 이슈는 클로즈 하겠습니다!!
