### ISSUE TITLE
Pull requests 된 파일들은 merge 되어야 코드를 써볼 수 있는 건가요??

### ISSUE THREAD

**Issue by Exist95** [haileyport/PaldoGames#5]
Pull requests 된 파일들은 merge 되어야 코드를 써볼 수 있는 건가요?? 
깃허브로 진행되는 협업이 처음이라 익숙하지 않네요 ㅠ

**Comment by devyuriii** [comment]
3가지 정도 방법이 떠오르네요!

develop로 merge한 후에
  1. 개인 브랜치에서 `git pull origin develop` 사용하여 develop 의 변경사항을 가져와서 사용
  2. develop 브랜치로 이동하셔서 사용
`git switch develop`
`git pull`

Merge 이전에
3. PR 올려주신 분의 브랜치로 이동해서 사용
`git switch branch-name`

1번을 추천 드리지만, 병합 전 사용을 해보고 싶으셔서 2번으로 사용하실 경우 **해당 브랜치의 파일을 변경하지 않도록 주의**해주시면 됩니다!
