### ISSUE TITLE
login 페이지가 index.js에 들어가는 게 좋을까요?

### ISSUE THREAD

**Issue by hongdahee** [haileyport/PaldoGames#6]
login 페이지가 첫 화면으로 보여야 하는데 index.js 안에 들어가는 게 좋을까요? 의견 부탁 드립니다~!

**Comment by devyuriii** [comment]
지금은 메인화면 내용을 index.js에서 불러오고 있네요!

로그인 여부에 따라서
비로그인-로그인창
로그인-메인화면
으로 보여줄 수 있도록 index.js를 구성하면 어떨까요?

index.js가 너무 길어질까요...

**Comment by Exist95** [comment]
index.js 안에 들어가는 게 좋을 것 같네요!

**Comment by leezer94** [comment]
로그인 컴포넌트를 따로 구성해서 index.js 에서 해당 컴포넌트를 호출하면 코드 길이도 한두줄 정도로 해결되고 , 
개인 로그인 여부을 상태 혹은 로컬 스토리지 로 관리하면 로그인 상태가 true 일때만 Home 컴포넌트를 보여준다 라는 로직으로 하면 될 것 같습니다!

**Comment by hongdahee** [comment]
건희님 말씀대로 로그인 컴포넌트를 따로 구성하는 게 좋은 거 같습니다!
