### ISSUE TITLE
검색 아이콘 크기 이슈

### ISSUE THREAD

**Issue by HA-SEUNG-JEONG** [haileyport/PaldoGames#69]
사실 이슈라 하기에는 좀 그렇지만..?

최초 로그인 시에 커뮤니티로 진입하면 

![image](https://user-images.githubusercontent.com/88266129/192661176-a990ffd5-1043-4618-9f3e-b7b27f579770.png)

이렇게 검색 아이콘이 커지는 현상이 있어서 몇 차례 로그아웃하고 다시 로그인 해도 똑같은 거 같아요!

**Comment by devyuriii** [comment]
현재 수정 버전으로 업데이트 대기 중입니다! 제보 감사해요~
