### ISSUE TITLE
각 게임마다 포인트 계산이 필요합니다.

### ISSUE THREAD

**Issue by Exist95** [haileyport/PaldoGames#8]
각 게임을 클리어 할 때마다 지급되는 포인트를 정해봐야 할 것 같네요!!
의견 있으시면 남겨주세요~

**Comment by devyuriii** [comment]
로또에 사용할 포인트가 얼마인지 정해지면 그걸 기준으로 정해야겠는데요!

지난번에 정한 난이도 (구구단 < 끝말잇기 < 숫자야구) 별로 쌓은 점수*N해주면 좋을듯 해요.

**Comment by leezer94** [comment]
예를 들어서, 

구구단 10판 -> 로또 1번 구매 가능

구구단, 끝말잇기 같은 경우는 실패 지점 까지 점수를 1점 같이 낮은 점수를 부여하는 식으로 하거나, 
혹은 다희님 말씀처럼 플레이 가능 한 판 수를 정해놓고 그 판 통계, 합 , 혹은 최고점수 부여 이런 로직이 좋을것 같습니다


끝말잇기 8 판  -> 로또 1번 구매 가능

숫자야구 6판 -> 로또 1 번 구매 가능

이런식으로 치환하면 어느정도 얻을 수 있는 포인트가 나오지 않을까 싶습니다.

**Comment by hongdahee** [comment]
로또를 너무 쉽게 할 수 있으면 게임의 흥미가 떨어질 거 같아서 로또 구매 포인트를 비싸게 하는 게 좋을 거 같습니다

**Comment by Exist95** [comment]
로또를 너무 비싸게 하면 흥미가 떨어질 수 있지도 않을까요??

**Comment by devyuriii** [comment]
숫자야구는 기회가 10회고 4자리수 맞추는 게 쉽지 않아서
숫자야구 성공 기준으로 3회 하면 로또 1회 하면 좋겠습니당.

실패하면 점수 안 드리구요

**Comment by leezer94** [comment]
끝말잇기 경우,  + 사간제한 필요할것 같음
틀리는 케이스가 맞춤법이 틀린경우, 사전에 정의되지 않은 단어를 입력한 경우
총 기회는 3번
3번 ( 최고점수, 3판 점수 평균, 총점 )


점수 : 한판 클리어시 점수 미정

**Comment by hongdahee** [comment]
<구구단>
2~19단까지 랜덤으로 10문제
10초 시간 제한, 목숨 세 개(7문제 맞히면 성공이라 포인트 지급)

**Comment by Exist95** [comment]
웰컴 포인트 : 5000
끝말잇기 : 200
구구단 : 200
슷자야구 : 400
로또 : 1000

**Comment by Exist95** [comment]
게임 한 판 금액 : 100
글쓰기 : 100
