### ISSUE TITLE
Window 환경에서 Chrome으로 접속 시 보안과 관련된 위험 경고가 발생합니다.

### ISSUE THREAD

**Issue by ninefloor** [haileyport/PaldoGames#81]
# 상황
페이지에 처음 접속할 때

# 문제
https로 연결되어 있는 상황임에도 크롬에서 접속하면 안된다고 강력한 경고창을 띄우네요. 크롬에서 알려주는 툴팁을 보니 위험 단계로, 세이프 브라우징에서 해당 사이트를 안전하지 않다고 신고한 것이라는 내용이 나옵니다. 제목에는 제가 경험한 windows 환경으로 명시했지만, Mac Chrome 환경에서도 동일한 이슈가 발생하는 것으로 확인됩니다.

![image](https://user-images.githubusercontent.com/77656241/193294742-e7040955-4ceb-4017-a3e9-1a48f300b38d.png)

**Comment by Exist95** [comment]
vercel을 사용하여 배포했기 때문에 발생하는 문제입니다. (무료 인증서이기 때문에)
크롬 보안 설정에서 세이프 브라우징을 해제하시면 접근 가능하실 거예요~
또는 windows 환경일 시,  엣지 브라우저로 접속하시면 원활하게 접근 가능하실 겁니다!!

**Comment by Exist95** [comment]
건희님 덕분에 해당 문제 해결했습니다.
이슈는 닫겠습니다. 이슈 올려주셔서 감사합니다!!
