### ISSUE TITLE
각 게임마다 게임시작 버튼과 게임방법 버튼을 넣으실 건가요??

### ISSUE THREAD

**Issue by Exist95** [haileyport/PaldoGames#9]
각 게임마다 게임시작 버튼과 게임방법 버튼을 넣으실 건가요??
![image](https://user-images.githubusercontent.com/96723716/188870049-004bd1b4-596d-40c4-8989-f2ec5d41dc3e.png)

**Comment by devyuriii** [comment]
게임 존 화면에서 게임 방법 보여주면 어떨까요?

호버 했을 때 `게임시작` `게임설명` 버튼이 뜨고,
시작 클릭 시 - 게임화면으로 이동
설명 클릭 시 - 게임설명 모달 open

이런 식으로요!

**Comment by Exist95** [comment]
은혜님 답변대로 진행하기로 했습니다~
